// Curated emoji set for the avatar picker.
// Default yellow skin tone only (no Fitzpatrick variants).
// Add to EMOJI_DATA to extend; the picker UI requires no changes.

export const EMOJI_CATEGORIES = [
  "smileys",
  "people",
  "animals",
  "music",
  "food",
  "activities",
  "travel",
  "symbols",
] as const;

export type EmojiCategory = (typeof EMOJI_CATEGORIES)[number];

export const CATEGORY_LABELS: Record<EmojiCategory, string> = {
  smileys: "Smileys",
  people: "People",
  animals: "Animals",
  music: "Music",
  food: "Food",
  activities: "Activities",
  travel: "Travel",
  symbols: "Symbols",
};

export interface EmojiEntry {
  emoji: string;
  category: EmojiCategory;
  keywords: string[];
}

export const EMOJI_DATA: EmojiEntry[] = [
  // ---- Smileys (30) ----
  { emoji: "😀", category: "smileys", keywords: ["grin", "happy", "smile"] },
  { emoji: "😃", category: "smileys", keywords: ["smile", "happy", "big"] },
  { emoji: "😄", category: "smileys", keywords: ["smile", "happy", "laugh"] },
  { emoji: "😁", category: "smileys", keywords: ["beaming", "grin", "teeth"] },
  { emoji: "😆", category: "smileys", keywords: ["laugh", "haha", "lol"] },
  { emoji: "😅", category: "smileys", keywords: ["sweat", "laugh", "nervous"] },
  { emoji: "🤣", category: "smileys", keywords: ["rofl", "laugh", "rolling"] },
  { emoji: "😂", category: "smileys", keywords: ["joy", "tears", "laugh", "cry"] },
  { emoji: "🙂", category: "smileys", keywords: ["smile", "slight"] },
  { emoji: "😉", category: "smileys", keywords: ["wink"] },
  { emoji: "😊", category: "smileys", keywords: ["blush", "smile", "happy"] },
  { emoji: "😍", category: "smileys", keywords: ["heart", "eyes", "love"] },
  { emoji: "🥰", category: "smileys", keywords: ["love", "hearts", "smile"] },
  { emoji: "😘", category: "smileys", keywords: ["kiss", "heart"] },
  { emoji: "😜", category: "smileys", keywords: ["wink", "tongue", "silly"] },
  { emoji: "🤪", category: "smileys", keywords: ["zany", "silly", "crazy"] },
  { emoji: "😎", category: "smileys", keywords: ["cool", "sunglasses"] },
  { emoji: "🤩", category: "smileys", keywords: ["star", "eyes", "wow", "excited"] },
  { emoji: "🥳", category: "smileys", keywords: ["party", "celebrate", "hat"] },
  { emoji: "😏", category: "smileys", keywords: ["smirk"] },
  { emoji: "🤔", category: "smileys", keywords: ["think", "hmm"] },
  { emoji: "😴", category: "smileys", keywords: ["sleep", "tired"] },
  { emoji: "😭", category: "smileys", keywords: ["cry", "sob", "sad"] },
  { emoji: "😱", category: "smileys", keywords: ["scream", "shock", "fear"] },
  { emoji: "🤯", category: "smileys", keywords: ["mind", "blown", "explode"] },
  { emoji: "🥺", category: "smileys", keywords: ["pleading", "puppy", "eyes"] },
  { emoji: "😈", category: "smileys", keywords: ["devil", "mischief", "evil"] },
  { emoji: "👻", category: "smileys", keywords: ["ghost", "spooky", "boo"] },
  { emoji: "💀", category: "smileys", keywords: ["skull", "dead"] },
  { emoji: "🤖", category: "smileys", keywords: ["robot", "bot"] },
  { emoji: "👽", category: "smileys", keywords: ["alien", "ufo"] },
  { emoji: "🤡", category: "smileys", keywords: ["clown"] },
  { emoji: "🎃", category: "smileys", keywords: ["pumpkin", "halloween", "jack"] },
  { emoji: "👑", category: "smileys", keywords: ["crown", "king", "queen", "royal"] },

  // ---- People & gestures (14) ----
  { emoji: "👍", category: "people", keywords: ["thumbs", "up", "like", "yes"] },
  { emoji: "👎", category: "people", keywords: ["thumbs", "down", "dislike", "no"] },
  { emoji: "👏", category: "people", keywords: ["clap", "applause"] },
  { emoji: "🙌", category: "people", keywords: ["raise", "hands", "hooray", "praise"] },
  { emoji: "🙏", category: "people", keywords: ["pray", "thanks", "please"] },
  { emoji: "🤘", category: "people", keywords: ["rock", "metal", "horns"] },
  { emoji: "✌️", category: "people", keywords: ["peace", "victory"] },
  { emoji: "🤞", category: "people", keywords: ["fingers", "crossed", "luck"] },
  { emoji: "🤟", category: "people", keywords: ["love", "you", "sign"] },
  { emoji: "👌", category: "people", keywords: ["ok", "perfect"] },
  { emoji: "💪", category: "people", keywords: ["muscle", "strong", "flex"] },
  { emoji: "🫶", category: "people", keywords: ["heart", "hands", "love"] },
  { emoji: "🤝", category: "people", keywords: ["handshake", "deal"] },
  { emoji: "👋", category: "people", keywords: ["wave", "hi", "bye"] },

  // ---- Animals (28) ----
  { emoji: "🐱", category: "animals", keywords: ["cat", "kitty"] },
  { emoji: "🐶", category: "animals", keywords: ["dog", "puppy"] },
  { emoji: "🐺", category: "animals", keywords: ["wolf"] },
  { emoji: "🦊", category: "animals", keywords: ["fox"] },
  { emoji: "🐻", category: "animals", keywords: ["bear"] },
  { emoji: "🐼", category: "animals", keywords: ["panda"] },
  { emoji: "🐨", category: "animals", keywords: ["koala"] },
  { emoji: "🐯", category: "animals", keywords: ["tiger"] },
  { emoji: "🦁", category: "animals", keywords: ["lion"] },
  { emoji: "🐮", category: "animals", keywords: ["cow"] },
  { emoji: "🐷", category: "animals", keywords: ["pig"] },
  { emoji: "🐸", category: "animals", keywords: ["frog"] },
  { emoji: "🐵", category: "animals", keywords: ["monkey"] },
  { emoji: "🦍", category: "animals", keywords: ["gorilla", "ape"] },
  { emoji: "🐔", category: "animals", keywords: ["chicken", "hen"] },
  { emoji: "🐧", category: "animals", keywords: ["penguin"] },
  { emoji: "🦅", category: "animals", keywords: ["eagle"] },
  { emoji: "🦉", category: "animals", keywords: ["owl"] },
  { emoji: "🦄", category: "animals", keywords: ["unicorn"] },
  { emoji: "🐲", category: "animals", keywords: ["dragon"] },
  { emoji: "🐙", category: "animals", keywords: ["octopus"] },
  { emoji: "🦋", category: "animals", keywords: ["butterfly"] },
  { emoji: "🐝", category: "animals", keywords: ["bee"] },
  { emoji: "🐞", category: "animals", keywords: ["ladybug"] },
  { emoji: "🦖", category: "animals", keywords: ["dinosaur", "trex"] },
  { emoji: "🐳", category: "animals", keywords: ["whale"] },
  { emoji: "🦈", category: "animals", keywords: ["shark"] },
  { emoji: "🐢", category: "animals", keywords: ["turtle"] },

  // ---- Music (15) ----
  { emoji: "🎤", category: "music", keywords: ["mic", "karaoke", "sing"] },
  { emoji: "🎙️", category: "music", keywords: ["mic", "studio", "podcast"] },
  { emoji: "🎧", category: "music", keywords: ["headphones", "audio"] },
  { emoji: "🎵", category: "music", keywords: ["note", "music"] },
  { emoji: "🎶", category: "music", keywords: ["notes", "music"] },
  { emoji: "🎸", category: "music", keywords: ["guitar", "rock"] },
  { emoji: "🎺", category: "music", keywords: ["trumpet", "brass"] },
  { emoji: "🎷", category: "music", keywords: ["sax", "saxophone"] },
  { emoji: "🎹", category: "music", keywords: ["piano", "keys", "keyboard"] },
  { emoji: "🥁", category: "music", keywords: ["drums", "drum"] },
  { emoji: "🎻", category: "music", keywords: ["violin", "fiddle"] },
  { emoji: "🪕", category: "music", keywords: ["banjo"] },
  { emoji: "🎚️", category: "music", keywords: ["slider", "mixer", "fader"] },
  { emoji: "📻", category: "music", keywords: ["radio"] },
  { emoji: "💿", category: "music", keywords: ["cd", "disc"] },

  // ---- Food & drink (20) ----
  { emoji: "🍕", category: "food", keywords: ["pizza"] },
  { emoji: "🍔", category: "food", keywords: ["burger", "hamburger"] },
  { emoji: "🌮", category: "food", keywords: ["taco"] },
  { emoji: "🌯", category: "food", keywords: ["burrito"] },
  { emoji: "🍣", category: "food", keywords: ["sushi"] },
  { emoji: "🍜", category: "food", keywords: ["ramen", "noodles"] },
  { emoji: "🍩", category: "food", keywords: ["donut", "doughnut"] },
  { emoji: "🍪", category: "food", keywords: ["cookie"] },
  { emoji: "🍦", category: "food", keywords: ["ice", "cream"] },
  { emoji: "🎂", category: "food", keywords: ["birthday", "cake"] },
  { emoji: "🍓", category: "food", keywords: ["strawberry"] },
  { emoji: "🍎", category: "food", keywords: ["apple"] },
  { emoji: "🍌", category: "food", keywords: ["banana"] },
  { emoji: "🍇", category: "food", keywords: ["grapes"] },
  { emoji: "🍿", category: "food", keywords: ["popcorn"] },
  { emoji: "☕", category: "food", keywords: ["coffee"] },
  { emoji: "🍺", category: "food", keywords: ["beer"] },
  { emoji: "🍻", category: "food", keywords: ["cheers", "beers"] },
  { emoji: "🍷", category: "food", keywords: ["wine"] },
  { emoji: "🍸", category: "food", keywords: ["cocktail", "martini"] },

  // ---- Activities & sports (14) ----
  { emoji: "⚽", category: "activities", keywords: ["soccer", "football"] },
  { emoji: "🏀", category: "activities", keywords: ["basketball"] },
  { emoji: "🏈", category: "activities", keywords: ["football", "american"] },
  { emoji: "⚾", category: "activities", keywords: ["baseball"] },
  { emoji: "🎾", category: "activities", keywords: ["tennis"] },
  { emoji: "🏐", category: "activities", keywords: ["volleyball"] },
  { emoji: "🥊", category: "activities", keywords: ["boxing", "gloves"] },
  { emoji: "🏆", category: "activities", keywords: ["trophy", "winner"] },
  { emoji: "🏅", category: "activities", keywords: ["medal"] },
  { emoji: "🎯", category: "activities", keywords: ["dart", "bullseye", "target"] },
  { emoji: "🎲", category: "activities", keywords: ["dice", "game"] },
  { emoji: "🎮", category: "activities", keywords: ["game", "controller"] },
  { emoji: "🎳", category: "activities", keywords: ["bowling"] },
  { emoji: "🎱", category: "activities", keywords: ["pool", "eight", "ball"] },

  // ---- Travel & places (10) ----
  { emoji: "🚗", category: "travel", keywords: ["car"] },
  { emoji: "🚀", category: "travel", keywords: ["rocket", "space"] },
  { emoji: "✈️", category: "travel", keywords: ["plane", "airplane"] },
  { emoji: "🚲", category: "travel", keywords: ["bike", "bicycle"] },
  { emoji: "🏍️", category: "travel", keywords: ["motorcycle"] },
  { emoji: "⛵", category: "travel", keywords: ["sailboat"] },
  { emoji: "🌍", category: "travel", keywords: ["earth", "globe", "world"] },
  { emoji: "🏝️", category: "travel", keywords: ["island", "beach"] },
  { emoji: "🏔️", category: "travel", keywords: ["mountain"] },
  { emoji: "🌋", category: "travel", keywords: ["volcano"] },

  // ---- Symbols & nature (19) ----
  { emoji: "❤️", category: "symbols", keywords: ["heart", "red", "love"] },
  { emoji: "🧡", category: "symbols", keywords: ["heart", "orange"] },
  { emoji: "💛", category: "symbols", keywords: ["heart", "yellow"] },
  { emoji: "💚", category: "symbols", keywords: ["heart", "green"] },
  { emoji: "💙", category: "symbols", keywords: ["heart", "blue"] },
  { emoji: "💜", category: "symbols", keywords: ["heart", "purple"] },
  { emoji: "🖤", category: "symbols", keywords: ["heart", "black"] },
  { emoji: "🤍", category: "symbols", keywords: ["heart", "white"] },
  { emoji: "💯", category: "symbols", keywords: ["hundred", "100", "perfect"] },
  { emoji: "🔥", category: "symbols", keywords: ["fire", "lit", "hot"] },
  { emoji: "⭐", category: "symbols", keywords: ["star"] },
  { emoji: "🌟", category: "symbols", keywords: ["glowing", "star"] },
  { emoji: "✨", category: "symbols", keywords: ["sparkles"] },
  { emoji: "⚡", category: "symbols", keywords: ["lightning", "bolt"] },
  { emoji: "💥", category: "symbols", keywords: ["boom", "explode"] },
  { emoji: "🌈", category: "symbols", keywords: ["rainbow"] },
  { emoji: "☀️", category: "symbols", keywords: ["sun"] },
  { emoji: "🌙", category: "symbols", keywords: ["moon"] },
  { emoji: "🌊", category: "symbols", keywords: ["wave", "water", "ocean"] },
  { emoji: "💎", category: "symbols", keywords: ["gem", "diamond"] },
];
